---
######################
# Development values #
######################

# Enable persistence to avoid LedgerNotExistException errors when bookies restart
# Previously disabled (emptyDir) which caused data loss on bookie pod restarts
volumes:
  persistence: true

# Disable autoSkipNonRecoverableData now that we have persistent storage
# This setting was a workaround for missing ledgers
broker:
  configData:
    autoSkipNonRecoverableData: "false"

# In case you have to debug, you can enable toolset:
# components:
#   toolset: true
