namespace: rabbitmq

resources:
  - ../../base
  - rabbitmq-rbac.yaml
  - rabbitmq-install-v3.13.yaml
  - rabbitmq-cert.yaml
  - rabbitmq-ingress.yaml
  - rabbitmq-frontend.yaml

generators:
  - ./ksops-secret-generator.yaml

