apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-prod-rabbitmq-secret
    labels:
        app.kubernetes.io/name: rabbitmq-prod
        app.kubernetes.io/component: rabbitmq-server
type: Opaque
data:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:8D1gkdDgdCUVVemjMR5MgcayZQL1tGel7YInItaxjlkLo5qd6C7dW5sfptkdrmYaxt193aM3yLHCKTDi,iv:sIY9NvHgPUTxkvrEazvoSh9MkR2PcFvVtqai52reAYE=,tag:cMBsMCVfyVVKxEHhS7BffA==,type:str]
    rabbitmq-pass: ENC[AES256_GCM,data:nfCaUFKKrQsUEMl5WXMSOyS73zSpaWZYr40PQD5cvOqSBy7LVJlZQo7opo7J4H9ad3Hw9H3moMC+ZXHa,iv:N0QAgTWcnJpnJFpd5A9f+5dureZryZ0U2VUt0jjbxYk=,tag:0oTlNxHn4uVcv8m36wELZw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-prod-397611/locations/europe-west3/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-12-08T14:48:42Z"
          enc: CiQAhLiU4bxGdrNXyPdu7sfzAXzNPB61GwUJnaS8FRq9+0HL1NISSQDOezfyf+iKosE3SuxGQAeiBhtFTSqhQEHHGN1gGm6wYh2r4153wIyKEVqV74X9QgktkvLNY7BNYt2MC05UOnYSmfZBRiuRTrU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-08T14:48:42Z"
    mac: ENC[AES256_GCM,data:cuxI7N/WC9x7KmGy5kQvoL3DwEFtT/Kjp41Aj87azWRDlx3ySCcxl5xYjRVtNKq+zOKIYv5EQKJAisPA7QD5q0ECsKFoUhorxIs7EuzkL/81/XoE6+i7RGXgyn42zGST8m7EjThDJi7q6ev7+xXd0Ye3cCMsY+1Ba0mJOdyEMus=,iv:IN2TW2jZEyxa9HHnoPY8yeMV6igs2InRvesuS623XXE=,tag:nHHaOyB57+OgP5FDHYkhuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
