apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-dev-rabbitmq-secret
    labels:
        app.kubernetes.io/name: rabbitmq-dev
        app.kubernetes.io/component: rabbitmq-server
type: Opaque
data:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:5JzVLIICE1SVOt1ySY+Nf5w0tNmXGk/jULpVrNo+ffuam1uzz1W+gppEPNDmINfdjHUXg4mYEswYpWtm8sIPc8cyLy/csAhj6dHV+WvTaDmdjsgMbT5j5A==,iv:PUCZBTQEwyTHfYfZAwyndT00PbX6i1R7PYuHsXLNImk=,tag:4Zkfi7wP207IavXGrepapA==,type:str]
    rabbitmq-pass: ENC[AES256_GCM,data:MaFCunGRH73cQ1a2724Vg0OZ1cOQ3jfYDzdt5nytKIpxpaGUWwQALHb47q61bvsaGAU8dNwoXsOiq5tMOgZQ6j8NbogR0ONdh7/Lg9DGxaxmk22CxLJl1w==,iv:Q2Bn257ez4HZ12ReYS/xkQ7qtl36wy5amfrvtd4FzgM=,tag:Vh95Awgw6xzZdBjfOKTCHw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-sandbox/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-11-17T17:17:10Z"
          enc: CiQAQ7huFoinFpfX6Lk+acoav+ycOh7FupfBEOL7RfHu/OuoyCISSQC//Ayi6Tr6bG2NBkw6M8PvabvjOITbvj/idPidq8sobZtJlA8RZhs4QU7021g7zEpGNMtA1f82D/y60L0mocyxypOfwdFTNqs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-17T17:17:11Z"
    mac: ENC[AES256_GCM,data:k83GD8a0wn1VxDjh+KYLk4OyoAY0tfQkjoydTF4tZGb2xVcg1mUxb9CnTOXO1CVofRXnxSyY3WHZti1s3DK2aBumZBkHK76w6zivmX6A+RY78JwfLeoXPIm2KJoO3QhOfOfZLw9b6fCGHKrneA+0JWWNjSHYV36VvwxUeZLWdh8=,iv:CzM4mUK88kRtplctdkLu7W1rljkR81cFmRSMs+cMqWI=,tag:6jpl/Ekx5VrYXA0iQ2H/2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
