---
# Source: rabbitmq/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-staging-rabbitmq-config
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus,rabbitmq_mqtt].
  rabbitmq.conf: |
      ## Clustering
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      # Use the Pods hostname instead of IP addresses to create a cluster.
      # The Pod IP doesn't work with persistence because new Pods get a new IP addresses,
      # that doesn't have access to existing data after the node name has changed.
      cluster_formation.k8s.address_type = hostname
      cluster_formation.node_cleanup.interval = 10
      # Set to false if automatic removal of unknown/absent nodes
      # is desired. This can be dangerous, see
      #  * http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup
      #  * https://groups.google.com/forum/#!msg/rabbitmq-users/wuOfzEywHXo/k8z_HWIkBgAJ
      cluster_formation.node_cleanup.only_log_warning = true
      cluster_partition_handling = autoheal
      ## queue master locator
      queue_master_locator = min-masters
      ## The default "guest" user is only permitted to access the server
      ## via a loopback interface (e.g. localhost)
      ## See http://www.rabbitmq.com/access-control.html#loopback-users
      loopback_users.guest = false
      # Enable MQTTS
      mqtt.listeners.ssl.default        = 8883
      ssl_options.cacertfile            = /etc/rabbitmq/ca/ca.crt
      ssl_options.certfile              = /etc/rabbitmq/certs/tls.crt
      ssl_options.keyfile               = /etc/rabbitmq/certs/tls.key
      ssl_options.verify                = verify_none
      ssl_options.fail_if_no_peer_cert  = false
      # Disable TCP without TLS
      listeners.tcp = none
---
# Source: rabbitmq/templates/service-discovery.yaml
# This headless service allows communication between RabbitMQ nodes via hostname instead of IP addresses.
# The clusterIP is set to None.
# See: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-staging-rabbitmq-discovery
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
spec:
  ports:
  - name: clustering
    port: 25672
  - name: prometheus
    port: 15692
  - name: mqtts
    port: 8883
  - name: http
    port: 15672
  selector:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
  type: ClusterIP
  clusterIP: None
---
# Source: rabbitmq/templates/service.yaml
# This services is used to connect to the RabbitMQ using Port Forwarding
# or expose an external IP and run RabbitMQ cluster behind a LoadBalancer.
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-staging-rabbitmq-svc
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
spec:
  ports:
  - name: clustering
    port: 25672
  - name: prometheus
    port: 15692
  - name: mqtts
    port: 8883
  - name: http
    port: 15672
  selector:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
  type: ClusterIP
---
# Source: rabbitmq/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-staging-rabbitmq
  labels: &RabbitMQDeploymentLabels
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
spec:
  selector:
    matchLabels: *RabbitMQDeploymentLabels
  serviceName: rabbitmq-staging-rabbitmq-discovery
  replicas: 1
  updateStrategy:
      # https://www.rabbitmq.com/upgrade.html
      # https://cloud.google.com/kubernetes-engine/docs/how-to/updating-apps
      type: RollingUpdate
  template:
    metadata:
      labels: *RabbitMQDeploymentLabels
    spec:
      serviceAccountName: rabbitmq-staging-serviceaccount
      terminationGracePeriodSeconds: 180
      initContainers:
      # This init container copies the config files from read-only ConfigMap to writable location.
      - name: copy-rabbitmq-config
        image: gcr.io/cloud-marketplace/google/rabbitmq/debian11:3.11
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -euc
        - |
          # Remove cached erlang cookie since we are always providing it,
          # that opens the way to recreate the application and access to existing data
          # as a new erlang will be regenerated again.
          echo ${RABBITMQ_ERLANG_COOKIE} > /var/lib/rabbitmq/.erlang.cookie
          chmod 600 /var/lib/rabbitmq/.erlang.cookie

          # Copy the mounted configuration to both places.
          cp /rabbitmqconfig/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
          # Change permission to allow to add more configurations via variables
          chown :999 /etc/rabbitmq/rabbitmq.conf
          chmod 660 /etc/rabbitmq/rabbitmq.conf
          cp /rabbitmqconfig/enabled_plugins /etc/rabbitmq/enabled_plugins
        volumeMounts:
        - name: configmap
          mountPath: /rabbitmqconfig
        - name: config
          mountPath: /etc/rabbitmq
        - name: rabbitmq-staging-rabbitmq-pvc
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-staging-rabbitmq-secret
              key: rabbitmq-erlang-cookie

      containers:
      - name: rabbitmq
        image: "gcr.io/cloud-marketplace/google/rabbitmq:3.13"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: JAVA_OPTS
          value: >-
                -Dlog4j2.formatMsgNoLookups=true
                -Dlog4j2.disable.jmx=true
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_USE_LONGNAME
          value: 'true'
        - name: RABBITMQ_NODENAME
          value: 'rabbit@$(MY_POD_NAME).rabbitmq-staging-rabbitmq-discovery.rabbitmq.svc.cluster.local'
        - name: K8S_SERVICE_NAME
          value: 'rabbitmq-staging-rabbitmq-discovery'
        - name: K8S_HOSTNAME_SUFFIX
          value: '.rabbitmq-staging-rabbitmq-discovery.rabbitmq.svc.cluster.local'
        # User name to create when RabbitMQ creates a new database from scratch.
        - name: RABBITMQ_DEFAULT_USER
          value: 'rabbit'
        # Password for the default user.
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-staging-rabbitmq-secret
              key: rabbitmq-pass
        ports:
        - name: clustering
          containerPort: 25672
        - name: amqp
          containerPort: 5672
        - name: amqp-ssl
          containerPort: 5671
        - name: prometheus
          containerPort: 15692
        - name: http
          containerPort: 15672
        volumeMounts:
        - name: config
          mountPath: /etc/rabbitmq
        - name: rabbitmq-staging-rabbitmq-pvc
          mountPath: /var/lib/rabbitmq
        - name: mqtts-certs
          mountPath: /etc/rabbitmq/certs
          readOnly: true
        - name: root-ca
          mountPath: /etc/rabbitmq/ca
          readOnly: true
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 20
          timeoutSeconds: 30
          periodSeconds: 60
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                # Wait for the RabbitMQ to be ready.
                until rabbitmqctl node_health_check; do
                  sleep 5
                done

                # By default, RabbitMQ does not have Highly Available policies enabled,
                # using the following command to enable it.
                rabbitmqctl set_policy ha-all "." '{"ha-mode":"all", "ha-sync-mode":"automatic"}' --apply-to all --priority 0
      
      volumes:
      - name: configmap
        configMap:
          name: rabbitmq-staging-rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
      - name: mqtts-certs
        secret:
          secretName: rabbitmq-staging-mqtt-cert-secret
      - name: root-ca
        configMap:
          name: rabbitmq-staging-ca
          items:
            - key: ca.crt
              path: ca.crt
      - name: config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-staging-rabbitmq-pvc
      labels: *RabbitMQDeploymentLabels
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
---
# Source: rabbitmq/templates/application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "rabbitmq-staging"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAYAAACKAxD9AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAByBJREFUeNrtnc1vXFcZh5/33vmwO7E9sWMmJCUNStJCDC1VQpWIBasKypJdV6hCtCRUsOgGIbHlD2BBsoANFWuWbCoVhCiofEihiJakoU1o4yI3cdLUdjzje18W5zodCrZnPCfzld8jjSzZ8tG55z73Pefc+953zN0RItEQCIkgJIKQCEIiCIkgtqUUtbUzVsYpA4Z3pKGR41RZ5cd92Me+YAlrlHFScgyDLfu5+TfDcTISWpzzXCLsxFmr4czg1DHSbYb44xEpp8VV4IPoR3fGjHNtgq0zjbMXZwJIO2wlA+7gLAM37/72u2Z9kbdPWC83lPJnrZI59XKJQziP4MwDk4VgO189RoqTYVzNc97cyHmr8lN/L+YBXv+GlepVPp0ahzEeBGZxKoUIvmMPw3E0gUWMf+Q57yzdYanxc88UETYv5xKzScZJcp4EngLmgfW2wLo9TgpkOMuJcbGS8gt+YL/kR96KdYBzNabJeBr4Ks5+YE/Rt06vgLQ4nn/hvJokvNSo8SvgQ4nw0Yk8ADxZfI710FID2Ae8zjKvrXzTrtR+5qu9dO3WM2YzVVLgEeCLwOlenQKmgGWcP4ybCEmPIhwCvgZ8NkJfZoDj5JyqlTnYc2N1qhgLwBPAoUjjdQRnAafB9yzhh2YSIYjwALD/v36ze8rA3iI61Ho+sowUp4HzKWA64pjNAXO02EMLiVCwAax9bHG167Vn8f9plPsbLdJC1Frk+yUGTJMzRTY+92FiHIhHHuSkR6Hae1UqPha5j2WgxBg9wR82o73LFX0nUSaPLKu3tSsRxHghEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSIT/S+yXYMWIimBtn2HG7/ZWItwTCRKMJFJE2KyG1iTuK+wZsI7RZGp8Xo0ftoiwB5jHmYmgVVq0N0XcwqIVoI6zh5sd12qUCF3yEM4TwDGet1qPR5YAnwEeB+oR+7gPOAUs0ByfyaE0ZP2ZJlRoO8EGl/i2/XMj43bm5NV0+6vPAXfy3ElSA0v5HPAYoezfZMQ+zgIngGU2uMZz9jYJeZ6RJzawCysssI0M4w7nuq9TOUwibF5dNeArOEeAi6WEa6Uwx5d2+Gc3I0+MKjBXlP77AjARuZ8PAEdxJouI8w7O+4nRIlb9p+6jeigTDO8CrwBXAMzMvMPSuqUhjFIJcLj4PApcKxZ7nczHWXHiD+BRp4N2ysVUUwcWgBs414pFaTqg8doU4RLOKmds5d3b3HLvPDIMowjtzLWF9U6uNC9OxmQf+1gHqnxUHnAQkTQHEpxPEEoa1w/WeBm4Oi4ipMWqf9gX3LUh6cthQt3LDzEudCOCbjGPHzVCOePyKG8fRW9kRRStdLtekQjjSdfPaySCJJAIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgpAIIg4lDcGucWAdWAaW2Dln0QlpZVVC8she4n5VsUQYEE1gEXgVeBnjBs4EW+ctbmAkOA3gKCEl/jFCEkm7KBJhhCJBE3gD+C3we+DPJNwip4pvcTLDOwcGzOJcBm4S8gsfJnzRuikijBZ3CCn2vybhPHBprUk6mdzNYrZtBGJxhcXGJJeThLdx3sL4Os5+TQ2jx03gAvAnzvkbAJMhV7AjPhl+tDhrr/kGTTMWgC8T/0Uc7RruMUvAKxh/5ztW3nUrP/FscY03ca4A17V9HD3WikXi9V5H78CL3ix2HTeKdiXCiC0WHcipRKjjYKy3LRwlwoiRAx5p9HKgRRfrDIkwPITdgUdraxBvUUsEIRGERBASQUiEe7R9zIlXFDR2exKhrzsGRQRFUUJOQeXuA+TemADmCTUhJcIIUcXYB8zQijB+zl7gIP2t+/Q/6Olj98zjnMZYosnru27leStnTY6nxrFBRwNFhN3RIDw2PsU6jV23knE8NZ4CPg+RJhlFhL6SEgp6nga+5c/ZBYOrGKs45S0XklYkrjgTudNIjJPAlwhpa0iE0V0wPgocNfgr8BvCo+Stcxa9yFk0DiShLPAx4BAMR2FvidBbZJgiVF+t4KywfUm7vMhnrBe7hNlhkUAixKEOnNzl/Qgkwngx8jeYtGsQEkFIBCERhEQQEkFIBCERhEQQEkFIBCERhEQQAxchQU8wh40USLes5XRPRDAyQok5MTy0gFaRGte3iLACvKexHxrKwCpwoyjA0TGlHiPCdZy/FB14kPBN6hs6HwNhAngfuAhcxLjdTxEuAy9i/A3ncYzZYm4yBvwu333E5lgbobbTS8AfcRa7asS9x/P1fTNucQTnBKGYZFpMORKhfyLkxZrg38DvOO9dT9e9iwBw1ibJmQWq0SoLiW51yAnFQJc4763BiCDu+/sIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgri/+Q/aXcSzrpbC2QAAAABJRU5ErkJggg==
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "rabbitmq", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "rabbitmq-staging"
spec:
  descriptor:
    type: RabbitMQ
    version: "3.13"
    description: |-
      RabbitMQ is an open source messaging system that implements the Advanced Message Queueing Protocol to serve a variety of messaging applications.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/rabbitmq/).
      Additional support is available on [community forums](https://groups.google.com/forum/#!forum/rabbitmq-users).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy RabbitMQ'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md
    - description: 'RabbitMQ documentation'
      url: https://www.rabbitmq.com/documentation.html
    - description: 'RabbitMQ Getting Started Tutorials'
      url: https://www.rabbitmq.com/getstarted.html
    notes: |-
      # Get authentication credentials for the cluster

      ```shell
      gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]
      ```
      where:
      * `[CLUSTER_NAME]` is the name of the cluster for this application
      * `[CLUSTER_ZONE]` is the zone, in which the cluster is operating

      Please read [here](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster) for more information.

      <!--- ALL THIS BELOW IS COPIED FROM README.MD -->

      # Get the status of the cluster

      By default, the application does not have an external IP address. To get the
      status of the cluster, use `kubectl` to execute `rabbitmqctl` on the master
      node:

      ```
      kubectl exec -it rabbitmq-staging-rabbitmq-0 --namespace rabbitmq -- rabbitmq-diagnostics cluster_status
      ```

      # Authorization

      The default username is `rabbit`. Use `kubectl` to get the generated password:

      ```shell
      kubectl get secret/rabbitmq-staging-rabbitmq-secret \
        --namespace rabbitmq \
        --output=jsonpath='{.data.rabbitmq-pass}' | base64 --decode
      ```

      # (Optional) Expose the RabbitMQ service externally

      By default, the application does not have an external IP. To create an
      external IP address for the service, run the following command:

      ```
      kubectl patch service/rabbitmq-staging-rabbitmq-svc \
        --namespace rabbitmq \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

      > **NOTE:** It might take some time for the external IP to be provisioned.

      # Access RabbitMQ service

      **Option 1:** If you run your RabbitMQ cluster behind a LoadBalancer, run the
      following command to get the external IP of the RabbitMQ service:

      ```
      SERVICE_IP=$(kubectl get service/rabbitmq-staging-rabbitmq-svc \
        --namespace rabbitmq \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}:15672"
      ```

      To access the RabbitMQ management UI, open `http://[EXTERNAL-IP]:15672`, where
      `[EXTERNAL-IP]` is the output of the command above.

      **Option 2:** Use port forwarding:

      ```
      kubectl port-forward svc/rabbitmq-staging-rabbitmq-svc --namespace rabbitmq 15672
      ```

      To access the RabbitMQ management UI, open [http://127.0.0.1:15672](http://127.0.0.1:15672).

      <!--- ALL THIS ABOVE IS COPIED FROM README.MD -->
  info:
  - name: RabbitMQ external IP
    type: Reference
    valueFrom:
      serviceRef:
        name: rabbitmq-staging-rabbitmq-svc
  - name: RabbitMQ username
    value: 'rabbit'
  - name: RabbitMQ password
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-pass
        name: rabbitmq-staging-rabbitmq-secret
  - name: Erlang cookie
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-erlang-cookie
        name: rabbitmq-staging-rabbitmq-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: "rabbitmq-staging"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: v1
    kind: ServiceAccount
