apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-staging-serviceaccount
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-staging-rabbitmq-endpoint-reader
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-staging-rabbitmq-endpoint-reader
  labels:
    app.kubernetes.io/name: rabbitmq-staging
    app.kubernetes.io/component: rabbitmq-server
subjects:
- kind: ServiceAccount
  name: rabbitmq-staging-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-staging-rabbitmq-endpoint-reader
