apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-staging-rabbitmq-secret
    labels:
        app.kubernetes.io/name: rabbitmq-staging
        app.kubernetes.io/component: rabbitmq-server
type: Opaque
data:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:hnK4sbyG8GJpaonoVUeJngOioyLHcHHdKulSybuF2O4Y0G27Kng/Idc/4JZTmIrggtF0U0j/IHpaBzIF8n8EqSEPFtaNZihi2zBO9W3rlJ/J//gF/mhYDQ==,iv:a8W1wtSBW+G4jucd0zHt9P8bMJ2WOSWD5+GxjMNm70o=,tag:xBaCstvJ3A7ixsQMD9PHbQ==,type:str]
    rabbitmq-pass: ENC[AES256_GCM,data:JeckUMSIy/x0P0BA4kL8/OyWWUyGdwSZY0nNkh4VaqmqCAcqcsRJKQUiX1+kpoBvGKsJUQqflXJ3ArXlg8e1RZoD+HA2SbCos2i1sBZ7LwD3a1g4bAdHAQ==,iv:V2JRwyl7OVAVA1qt7O3w0sxRgiTWW15AFxuy0N4d5I8=,tag:RO1dMway2W551NpnFl2bvQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/apc-staging-388907/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-10-30T12:17:55Z"
          enc: CiQAUhREB14ZMGCA2Mw2I6S0uY/n6cBMXv97e0idJYpYOs7ZVpASSQD4ANZe7WB90e4yw73UX1f+MGoqzxLvVaaSTNPAKJJqvFktadzTaclYsuNjCmUrLOaZFLp81Ol9DXsYhHUL8s3jaTQIuDh0O1A=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-10-30T12:17:56Z"
    mac: ENC[AES256_GCM,data:Pjb0wae0yIi8u1r7UhZlolTPwVvlDuY0ZPkE6Q8HKIHh9c5QfR+I29pcfJxTGNIfsYAvrKurOPM9ghQsf4yI4C7zhDMHA/Re/m2WHDkRby78bH+q0W7rnPMAo5Sxcw8CdnTyPlugyni0vbKRm5b/soaMgWS0uyklUXhQPChV64Q=,iv:502/VV9tPj9LZoQpCmiE4e2HrRRiUzrwd+xJOBW1ZBs=,tag:wPSLHgbBe5nxKilVfvPjZg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0-rc.1
